openapi: 3.0.3
info:
    title: Infisical API
    description: Infisical secret management platform API
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /api/v1/platform/projects:
        post:
            tags:
                - projects
            summary: createProject projects
            description: Create a new project.
            operationId: projects#createProject
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateProjectPayload'
                        example:
                            name: hay
                            orgId: Id eveniet atque sed.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Project'
                            example:
                                id: Eius maxime nemo doloremque magni velit.
                                name: Hic mollitia ut ea.
                                orgId: Tempora ut sunt nihil aut sunt et.
    /api/v1/platform/projects/health:
        get:
            tags:
                - projects
            summary: getHealth projects
            description: Health check for the projects service.
            operationId: projects#getHealth
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Voluptates rerum maxime aut placeat rerum quos.
                            example: Laudantium porro.
    /api/v1/secret-manager/secrets:
        get:
            tags:
                - secrets
            summary: listSecrets secrets
            description: List secrets for an environment.
            operationId: secrets#listSecrets
            parameters:
                - name: projectId
                  in: query
                  description: Project ID
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Project ID
                    example: Aperiam optio ea molestias quibusdam nisi quia.
                  example: Eos rerum laborum maiores architecto.
                - name: environment
                  in: query
                  description: Environment slug
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Environment slug
                    example: Illo dicta exercitationem est.
                  example: Accusamus ut dolorem nemo.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SecretResultCollection'
                            example:
                                - environment: Magnam quidem necessitatibus minima quia.
                                  id: Est et omnis nobis.
                                  key: Inventore similique quae est nesciunt aperiam dolorem.
                                  projectId: Dolore laudantium occaecati accusamus mollitia voluptas vero.
                                  value: Animi unde nihil enim.
                                - environment: Magnam quidem necessitatibus minima quia.
                                  id: Est et omnis nobis.
                                  key: Inventore similique quae est nesciunt aperiam dolorem.
                                  projectId: Dolore laudantium occaecati accusamus mollitia voluptas vero.
                                  value: Animi unde nihil enim.
        post:
            tags:
                - secrets
            summary: createSecret secrets
            description: Create a new secret.
            operationId: secrets#createSecret
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Secret'
                        example:
                            environment: Qui eum quos eum pariatur.
                            key: DATABASE_URL
                            projectId: Deleniti itaque voluptatum.
                            value: Reiciendis minima.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Secret3'
                            example:
                                environment: Ipsa placeat.
                                id: Aperiam vel velit repellendus aliquam.
                                key: Quia adipisci.
                                projectId: Corrupti est et.
                                value: Tempore corrupti.
    /api/v1/secret-manager/secrets/{id}:
        delete:
            tags:
                - secrets
            summary: deleteSecret secrets
            description: Delete a secret by ID.
            operationId: secrets#deleteSecret
            parameters:
                - name: id
                  in: path
                  description: Secret ID
                  required: true
                  schema:
                    type: string
                    description: Secret ID
                    example: Dolor labore.
                  example: Est aut aliquam placeat ducimus sit.
            responses:
                "204":
                    description: No Content response.
        get:
            tags:
                - secrets
            summary: getSecret secrets
            description: Get a secret by ID.
            operationId: secrets#getSecret
            parameters:
                - name: id
                  in: path
                  description: Secret ID
                  required: true
                  schema:
                    type: string
                    description: Secret ID
                    example: Corrupti necessitatibus quasi enim.
                  example: Omnis exercitationem optio laborum voluptates sit.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Secret4'
                            example:
                                environment: Quia consequuntur id quasi nostrum.
                                id: Consequatur et temporibus incidunt earum.
                                key: Iste distinctio.
                                projectId: Mollitia velit eum rem sed corrupti ducimus.
                                value: Consequatur ea consequatur provident aliquam mollitia.
        patch:
            tags:
                - secrets
            summary: updateSecret secrets
            description: Update an existing secret.
            operationId: secrets#updateSecret
            parameters:
                - name: id
                  in: path
                  description: Secret ID
                  required: true
                  schema:
                    type: string
                    description: Secret ID
                    example: Eum autem.
                  example: Aspernatur necessitatibus blanditiis.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateSecretRequestBody'
                        example:
                            key: Omnis autem quo ducimus facilis veritatis.
                            value: Eligendi quasi iusto.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Secret5'
                            example:
                                environment: Sed sint voluptatem et et ut.
                                id: Quis cupiditate nobis fugiat consectetur.
                                key: Necessitatibus aliquid alias nihil.
                                projectId: Expedita molestiae repudiandae veritatis.
                                value: Ipsa quibusdam vel cupiditate enim optio.
    /api/v1/secret-manager/secrets/health:
        get:
            tags:
                - secrets
            summary: getHealth secrets
            description: Health check for the secrets service.
            operationId: secrets#getHealth
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Doloremque qui minus consequatur non aut officia.
                            example: Deleniti sunt recusandae.
components:
    schemas:
        CreateProjectPayload:
            type: object
            properties:
                name:
                    type: string
                    description: Project name
                    example: "3"
                    minLength: 1
                orgId:
                    type: string
                    description: Organization ID
                    example: Tempora voluptas.
            example:
                name: q
                orgId: Necessitatibus qui harum ut quo.
            required:
                - name
                - orgId
        Project:
            type: object
            properties:
                id:
                    type: string
                    description: Project ID
                    example: Tempora numquam ut ea molestiae est.
                name:
                    type: string
                    description: Project name
                    example: Et veniam.
                orgId:
                    type: string
                    description: Organization ID
                    example: Voluptas occaecati quam placeat ut non.
            example:
                id: Accusantium aspernatur non repudiandae.
                name: Qui magni voluptatem sint sed.
                orgId: Quaerat neque dolor est.
            required:
                - id
                - name
                - orgId
        Secret:
            type: object
            properties:
                environment:
                    type: string
                    description: Environment slug
                    example: Veritatis nostrum ab quo accusantium.
                key:
                    type: string
                    description: Secret key
                    example: DATABASE_URL
                projectId:
                    type: string
                    description: Project ID
                    example: Quasi sit itaque libero labore ut vitae.
                value:
                    type: string
                    description: Secret value
                    example: Voluptates temporibus ut consequuntur.
            example:
                environment: Nam minus corrupti.
                key: DATABASE_URL
                projectId: Nobis in.
                value: Aut nisi autem.
            required:
                - key
                - value
                - environment
                - projectId
        Secret2:
            type: object
            properties:
                environment:
                    type: string
                    description: Environment slug
                    example: Repellendus blanditiis corrupti iusto non.
                id:
                    type: string
                    description: Secret ID
                    example: Voluptatem et veritatis ipsa cum est.
                key:
                    type: string
                    description: Secret key
                    example: Debitis voluptatem dolore quia corrupti unde.
                projectId:
                    type: string
                    description: Project ID
                    example: Est perferendis.
                value:
                    type: string
                    description: Secret value
                    example: Aperiam et mollitia mollitia officia molestiae odio.
            example:
                environment: Aut voluptas animi.
                id: Hic et velit temporibus ea necessitatibus.
                key: Iure aut.
                projectId: Cupiditate asperiores tenetur.
                value: Veniam sint quo quas velit.
            required:
                - id
                - key
                - value
                - environment
                - projectId
        Secret3:
            type: object
            properties:
                environment:
                    type: string
                    description: Environment slug
                    example: Sed pariatur sunt repudiandae voluptatibus quasi provident.
                id:
                    type: string
                    description: Secret ID
                    example: Voluptatem sunt et sed.
                key:
                    type: string
                    description: Secret key
                    example: Et officia ea rerum quidem velit at.
                projectId:
                    type: string
                    description: Project ID
                    example: Est neque officia aspernatur laudantium molestiae.
                value:
                    type: string
                    description: Secret value
                    example: Enim qui eum et.
            example:
                environment: Delectus ut.
                id: Ut libero tenetur.
                key: Officiis velit amet.
                projectId: Voluptatem est.
                value: Eaque omnis est.
            required:
                - id
                - key
                - value
                - environment
                - projectId
        Secret4:
            type: object
            properties:
                environment:
                    type: string
                    description: Environment slug
                    example: Inventore praesentium blanditiis soluta beatae occaecati.
                id:
                    type: string
                    description: Secret ID
                    example: Omnis veniam.
                key:
                    type: string
                    description: Secret key
                    example: Explicabo et sed.
                projectId:
                    type: string
                    description: Project ID
                    example: Impedit enim dignissimos sed magni accusantium facilis.
                value:
                    type: string
                    description: Secret value
                    example: Eum est consequatur velit eaque quibusdam id.
            example:
                environment: Enim molestias at.
                id: Ratione voluptas exercitationem maiores natus.
                key: Et eum dolores tempore ullam possimus quisquam.
                projectId: Consequatur autem pariatur.
                value: Sunt in.
            required:
                - id
                - key
                - value
                - environment
                - projectId
        Secret5:
            type: object
            properties:
                environment:
                    type: string
                    description: Environment slug
                    example: Porro et quia tempore quis.
                id:
                    type: string
                    description: Secret ID
                    example: Voluptas inventore est ut.
                key:
                    type: string
                    description: Secret key
                    example: Quam rem.
                projectId:
                    type: string
                    description: Project ID
                    example: Et quia eos incidunt.
                value:
                    type: string
                    description: Secret value
                    example: Quidem dolor recusandae voluptates et inventore.
            example:
                environment: Qui excepturi numquam est accusamus natus qui.
                id: Quod aut exercitationem enim consectetur dolor ut.
                key: Ex delectus.
                projectId: Voluptas nesciunt illum sed magni facere et.
                value: Laboriosam odio repellendus officiis.
            required:
                - id
                - key
                - value
                - environment
                - projectId
        Secret6:
            type: object
            properties:
                environment:
                    type: string
                    description: Environment slug
                    example: Quam eius doloribus dolorem odio similique.
                id:
                    type: string
                    description: Secret ID
                    example: Alias sed aut ut.
                key:
                    type: string
                    description: Secret key
                    example: Ratione aliquam quas expedita ipsam delectus.
                projectId:
                    type: string
                    description: Project ID
                    example: Dolor nulla dolore mollitia facilis sed.
                value:
                    type: string
                    description: Secret value
                    example: Corrupti et velit quod nihil dolor.
            example:
                environment: Exercitationem eligendi saepe et earum corporis.
                id: Omnis et ut aliquid atque ipsum vero.
                key: Suscipit velit molestias ratione itaque exercitationem voluptate.
                projectId: Voluptas culpa.
                value: Iste quia.
            required:
                - id
                - key
                - value
                - environment
                - projectId
        SecretResultCollection:
            type: array
            items:
                $ref: '#/components/schemas/Secret6'
            example:
                - environment: Magnam quidem necessitatibus minima quia.
                  id: Est et omnis nobis.
                  key: Inventore similique quae est nesciunt aperiam dolorem.
                  projectId: Dolore laudantium occaecati accusamus mollitia voluptas vero.
                  value: Animi unde nihil enim.
                - environment: Magnam quidem necessitatibus minima quia.
                  id: Est et omnis nobis.
                  key: Inventore similique quae est nesciunt aperiam dolorem.
                  projectId: Dolore laudantium occaecati accusamus mollitia voluptas vero.
                  value: Animi unde nihil enim.
        UpdateSecretRequestBody:
            type: object
            properties:
                key:
                    type: string
                    description: Secret key
                    example: Et in et quos eius soluta.
                value:
                    type: string
                    description: Secret value
                    example: Impedit adipisci voluptatem molestiae voluptas nemo.
            example:
                key: Unde modi.
                value: Voluptatibus officia magni et ducimus pariatur.
tags:
    - name: projects
      description: Service for managing projects.
    - name: secrets
      description: Service for managing secrets.
